version: '3.8'
services:
  entry-app:
    build:
      context: .
      dockerfile: ./apps/entry-app/Dockerfile
    ports:
      - '3000:80'

  manage-customers-app:
    build:
      context: .
      dockerfile: ./apps/manage-customers-app/Dockerfile
    ports:
      - '3001:80'

  view-customers-app:
    build:
      context: .
      dockerfile: ./apps/view-customers-app/Dockerfile
    ports:
      - '3002:80'
