version: '3.8'
services:
  entry-app:
    build: ./entry-app
    ports:
      - '3000:80'

  manage-customers-app:
    build: ./manage-customers-app
    ports:
      - '3001:80'

  view-customers-app:
    build: ./view-customers-app
    ports:
      - '3002:80'
